### Cek Ongkir JNE
POST https://rajaongkir.komerce.id/api/v1/calculate/domestic-cost
Content-Type: application/x-www-form-urlencoded
Accept: application/json
key: YFTyzVdi7ceed7179f94d649c0r7UqG2

origin=64999&destination=64942&weight=1000&courier=jne